### ISSUE TITLE
Power Stone 1

### ISSUE THREAD

**Issue by Shentokk** [toyoshim/iona-us#34]
When using a PS4 controller, the game does not recognize the Iona as being connected. It seems to work fine with Xbox One controllers.

I'd also like to add that this issue appears with Monkey Ball and Initial D 3 Export.

**Comment by toyoshim** [comment]
Hum.... curious.
USB and JVS are logically isolated, and would not affect each other....

**Comment by Shentokk** [comment]
![Screenshot 2022-07-03 17-22-52](https://user-images.githubusercontent.com/24884591/177062687-85cbe36b-4e52-4e5c-8a5d-da07ca48c5f9.png)
It seems this happens on Jambo Safari too after a few minutes of play. Only with the PS4 controller used. Other controllers aren't having this issue.

**Comment by toyoshim** [comment]
Let me merge this topic to #42 so that I can ensure if such stability issue still exist in v2 firmware
