### ISSUE TITLE
Keyboard mode for Typing of the Dead and Lupin THE TYPING

### ISSUE THREAD

**Issue by Shentokk** [toyoshim/iona-us#35]
Would it be possible to add a keyboard mode for these games or would it be impossible?

**Comment by toyoshim** [comment]
If they use JVS to take keyboard inputs, it's possible. But my quick research says they use maple I/F?

**Comment by Shentokk** [comment]
Gotcha. I figured as much, but it was worth asking to see. Thanks!

**Comment by toyoshim** [comment]
I asked this at my Twitter too, but it seems the original cab also use DC's keyboards over the Maple interface. So I think the game doesn't support it over JVS.

**Comment by toyoshim** [comment]
fyi, https://twitter.com/toyoshim/status/1542188870997274624?s=21&t=ZLNHhiUPTfFeN0euZRHipQ

**Comment by Shentokk** [comment]
Thank you. It seems like the Wingman SD is my best avenue for this with a maple adapter.
