### ISSUE TITLE
Can't get it to work with Namco System 12 (tekken tag tournament)

### ISSUE THREAD

**Issue by mpalpha** [toyoshim/iona-us#45]
I can't get it to work with Namco System 12 (tekken tag tournament) pcb. Do I need to do something not mentioned previously in the documentation?

**Comment by toyoshim** [comment]
just in case,
https://toyoshim.github.io/iona-us/troubleshoot_en
step by step trouble shooting hints are here.

and here you can find information to flip the signal level adjustment option.
https://toyoshim.github.io/iona-us/en

**Comment by toyoshim** [comment]
close as inactive reports
