### ISSUE TITLE
Not working with SEGA RingEdge 2

### ISSUE THREAD

**Issue by VampireSavior** [toyoshim/iona-us#48]
Hello, I and another person are having issues running the Ver 2.00 board with the SEGA RingEdge 2. The board will lag inputs and not allow games to be run due to the board. You can read more info [here ](https://www.arcade-projects.com/threads/ringedge-2-multi-games-crashing-after-boot.25503/). Is there any way you will be able to fix this issue? If you would like photos or videos let me know!

**Comment by toyoshim** [comment]
Can we merge this topic to #44 ?
