### ISSUE TITLE
8BitDo NEO GEO Controller Support

### ISSUE THREAD

**Issue by bmarvo** [toyoshim/iona-us#61]
This controller does not work, either in wireless mode with the dongle, or wired mode.

https://shop.8bitdo.com/products/8bitdo-neogeo-controller

**Comment by toyoshim** [comment]
Oh, good to know.
I'm also interested in this controller. So, I just order one now, and will try supporting it once I get it.

**Comment by toyoshim** [comment]
Fixed in the repository. 2.15+ will pick up this fix soon!
