### ISSUE TITLE
ナムコ タイムクライシス2（システム23）が認識しない

### ISSUE THREAD

**Issue by pizzzza19** [toyoshim/iona-us#75]
IONAのファームウェア：Ver2.22
接続コントローラー：Xbox One USB-A
基板：ナムコシステム23

JVS信号補正等どの設定を行っても基板とネゴシエーションせず、青いLEDが高速点灯したままタイムアウトする。
何故かTSS-I/Oモードではなくセガにするとネゴシエーション自体は完了するがサブボードのテスト画面の途中でフリーズ。IONA側のTESTとSERVICEボタンだけは正常認識する。

基板側DIPの2番目をONにするとポスト画面をスキップして強制的にゲームに入れるがコイン投入後数十秒でフリーズ。

NAOMI基板では全て順調でしたのでナムコ基板との相性がまだ未完成と思います。

**Comment by toyoshim** [comment]
タイムクライシスは、以下の設定で認識したかと思います。

JVS ID: namco ltd;JYU-PCB
画面座標入力数: 1
画面座標入力幅: 16

割り当てはマップはこちらをご確認ください。
https://github.com/toyoshim/iona-us/wiki/Gun-Shooting

タイムクライシスは1〜3まで調査していた時期があったのですが、デバッグに付き合ってくれていた方の環境で、Guncon3照準がうまくキャリブレーションできない問題が解決できず、presetの公開には至っていない現状です。

**Comment by toyoshim** [comment]
あー、古い方がありましたね。
#56 のdupで閉じます。
